### ISSUE TITLE
I get the following error when I execute get_problem_archive.py

### ISSUE THREAD

**Issue by ghost** [atheendra/download-topcoder-problem-archive#1]
Traceback (most recent call last):
  File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\get_problem_archive.py", line 132, in <module>
    download_new_ids(link, completed_ids_file)
  File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\get_problem_archive.py", line 52, in download_new_ids
    completed_ids = get_completed_problem_ids(completed_ids_file)
  File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\get_problem_archive.py", line 32, in get_completed_problem_ids
    infile = open(file, "r")
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by gaddevarunteja** [comment]
Waiting for reply

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\get_problem_archive.py", line 139, in <module>
    download_new_ids(link, completed_ids_file)
  File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\get_problem_archive.py", line 56, in download_new_ids
    current_ids = get_ids_from_website(link)
  File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\get_problem_archive.py", line 21, in get_ids_from_website
    pool = get_soup(link)
  File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\get_problem_archive.py", line 14, in get_soup
    html_page = response.read()
  File "C:\Python27\lib\socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "C:\Python27\lib\httplib.py", line 588, in read
    return self._read_chunked(amt)
  File "C:\Python27\lib\httplib.py", line 642, in _read_chunked
    raise IncompleteRead(''.join(value))
IncompleteRead: IncompleteRead(7737 bytes read)

**Comment by atheendra** [comment]
Unable to recreate this issue. Can you tell me how you're running it? I ran it this way, it worked:
python get_problem_archive.py -n 10

**Comment by ghost** [comment]
I ran like this python get_problem_archive.py even if I add -n 10 at the last it shows some windows error

Traceback (most recent call last):
  File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\get_pr
oblem_archive.py", line 139, in <module>
    download_new_ids(link, completed_ids_file)
  File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\get_pr
oblem_archive.py", line 59, in download_new_ids
    call(["mkdir", "-p", destination_dir])
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in **init**
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by atheendra** [comment]
The chunk error is a workaround. Unfortunately, I'm not sure it'll work, so you'll have to test it for me. The second bug you pointed out should be fixed.

**Comment by ghost** [comment]
It is showing the same error

Traceback (most recent call last):
File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\get_pr
oblem_archive.py", line 139, in 
download_new_ids(link, completed_ids_file)
File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\get_pr
oblem_archive.py", line 59, in download_new_ids
call(["mkdir", "-p", destination_dir])
File "C:\Python27\lib\subprocess.py", line 522, in call
return Popen(popenargs, *kwargs).wait()
File "C:\Python27\lib\subprocess.py", line 710, in init
errread, errwrite)
File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by atheendra** [comment]
Pull the latest changes. That code doesn't even exist now, if you notice.

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\download-topcoder-problem-archive-master\get_problem_archive.py", line 155, in <module>
    download_new_ids(link, completed_ids_file)
  File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\download-topcoder-problem-archive-master\get_problem_archive.py", line 78, in download_new_ids
    download_single_id(id, completed_ids_file)
  File "C:\Users\Varun\Downloads\download-topcoder-problem-archive-master\download-topcoder-problem-archive-master\get_problem_archive.py", line 62, in download_single_id
    exit_status = call(["gettc", id])
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in **init**
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by atheendra** [comment]
Read prerequisites. Specifically, gettc

**Comment by ghost** [comment]
gettc is not working because topcoder has changed links maybe
